version: '3.10'

services:
  db:
    image: mysql/mysql-server
    environment:
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'mysql123456'
      MYSQL_ROOT_PASSWORD: 'mysql123456'
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql  
      - ./docker/examples/my.cnf:/etc/my.cnf:ro
      - ./docker/examples/sqls:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - baizenet
  controller:
    image: baizeai/baize-ai:latest
    command: dbgpt start controller
    restart: unless-stopped
    networks:
      - baizenet
  api-server:
    image: baizeai/baize-ai:latest
    command: dbgpt start apiserver --controller_addr http://controller:8000 --api_keys EMPTY
    restart: unless-stopped
    depends_on:
      - controller
    networks:
      - baizenet
    ports:
      - 8100:8100/tcp
  webserver:
    image: baizeai/baize-ai:latest
    command: python3 dbgpt/app/dbgpt_server.py --disable_alembic_upgrade
    environment:
      # DATABASE SETTINGS
      - LOCAL_DB_TYPE=mysql
      - LOCAL_DB_USER=root
      - LOCAL_DB_PASSWORD=mysql123456
      - LOCAL_DB_HOST=db
      - LOCAL_DB_PORT=3306
      - LOCAL_DB_NAME=baizeai
      # ALLOWLISTED PLUGINS
      - ALLOWLISTED_PLUGINS=db_dashboard
      # LLM MODELS
      - LLM_MODEL=tongyi_proxyllm
      - TONGYI_PROXY_API_KEY=sk-1aa230e037da496da22eb0fe46b3580a
      - PROXY_SERVER_URL=https://dashscope.aliyuncs.com/api/v1/services/aigc/text-generation/generation
      - MODEL_SERVER=http://controller:8000
      - LIMIT_MODEL_CONCURRENCY=5
      - MAX_POSITION_EMBEDDINGS=4096
      # EMBEDDING SETTINGS EMBEDDING MODELS
      - EMBEDDING_MODEL=bge-large-zh
      - KNOWLEDGE_CHUNK_SIZE=500
      - KNOWLEDGE_SEARCH_TOP_SIZE=5
      # EMBEDDING SETTINGS Control whether to display the source document of knowledge on the front end.
      - KNOWLEDGE_CHAT_SHOW_RELATIONS=False
      # EMBEDDING SETTINGS Whether to enable Chat Knowledge Search Rewrite Mode
      - KNOWLEDGE_SEARCH_REWRITE=False
      # COMMANDS
      - EXECUTE_LOCAL_COMMANDS=False
      ### Chroma vector db config
      - VECTOR_STORE_TYPE=Chroma
      # SUMMARY_CONFIG
      - SUMMARY_CONFIG=FAST
      # LOG FATAL, ERROR, WARNING, WARNING, INFO, DEBUG, NOTSET
      - DBGPT_LOG_LEVEL=INFO
      - LANGUAGE=zh
    depends_on:
      - db
      - controller
      - api-server
    volumes:
      - app-data:/data  
      # Please modify it to your own model directory
      - ./models:/app/models
      - pilot-data:/app/pilot/data  
      - pilot-message:/app/pilot/message  
      - pilot-meta:/app/pilot/meta_data
    #env_file:
    #  - .env.template
    ports:
      - 65005:5000/tcp
    # webserver may be failed, it must wait all sqls in /docker-entrypoint-initdb.d execute finish.
    restart: unless-stopped
    networks:
      - baizenet
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
volumes:
  db-data:  
  app-data:  
  pilot-data:  
  pilot-message: 
  pilot-meta: 
networks:
  baizenet:
    driver: bridge
    name: baizenet